-- Created database and schema
CREATE OR REPLACE DATABASE CUSTOMER_DB;
USE DATABASE CUSTOMER_DB;
CREATE OR REPLACE SCHEMA PUBLIC;
USE SCHEMA PUBLIC;

-- 1. Raw table
CREATE OR REPLACE TABLE RAW_CUSTOMERS (
  CUSTOMER_ID INT,
  TENURE INT,
  MONTHLY_CHARGES FLOAT,
  SUPPORT_CALLS INT,
  DATA_USAGE FLOAT,
  PLAN_TYPE STRING,
  PAYMENT_METHOD STRING,
  LAST_RECHARGE DATE,
  CHURN STRING
);

-- 2. Cleaned table
CREATE OR REPLACE TABLE CLEANED_CUSTOMERS AS
SELECT *
FROM RAW_CUSTOMERS
WHERE MONTHLY_CHARGES > 0
  AND TENURE >= 0
  AND CHURN IN ('Yes','No');

-- 3. Feature store table
CREATE OR REPLACE TABLE CUSTOMER_FEATURES AS
SELECT
   CUSTOMER_ID,
   TENURE,
   MONTHLY_CHARGES,
   SUPPORT_CALLS,
   DATA_USAGE,
   DATEDIFF(day, LAST_RECHARGE, CURRENT_DATE()) AS DAYS_SINCE_RECHARGE,
   CASE
       WHEN TENURE < 6 THEN 'NEW'
       WHEN TENURE BETWEEN 6 AND 12 THEN 'MID'
       ELSE 'OLD'
   END AS TENURE_GROUP,
   IFF(CHURN = 'Yes',1,0) AS CHURN_LABEL
FROM CLEANED_CUSTOMERS;

-- 4. Train-test split
CREATE OR REPLACE TABLE TRAIN_CUSTOMERS AS
SELECT * FROM CUSTOMER_FEATURES
WHERE MOD(CUSTOMER_ID,5) <> 0;

CREATE OR REPLACE TABLE TEST_CUSTOMERS AS
SELECT * FROM CUSTOMER_FEATURES
WHERE MOD(CUSTOMER_ID,5) = 0;
